{
  "name": "lofi-player-widget",
  "version": "1.0.0",
  "description": "A lofi music player widget",
  "scripts": {
    "build": "echo 'No build step required'"
  },
  "dependencies": {
    "googleapis": "^92.0.0"
  }
}
